### ISSUE TITLE
Rasterio 1.4.2 does not work with AWS Lambda 3.12

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/titiler-md-demo#3]
```
#22 ERROR: process "/bin/sh -c python -c \"from handler import handler; print('All Good')\"" did not complete successfully: exit code: 1
------
 > [lambda 4/4] RUN python -c "from handler import handler; print('All Good')":
1.003 Traceback (most recent call last):
1.003   File "<string>", line 1, in <module>
1.003   File "/var/task/handler.py", line 5, in <module>
1.004     from app.main import app
1.004   File "/assets/lib/python3.12/site-packages/app/main.py", line 13, in <module>
1.005   File "/assets/lib/python3.12/site-packages/titiler/core/__init__.py", line 5, in <module>
1.005   File "/assets/lib/python3.12/site-packages/titiler/core/dependencies.py", line 10, in <module>
1.005   File "/assets/lib/python3.12/site-packages/rasterio/__init__.py", line 25, in <module>
1.005 ImportError: libexpat.so.1: cannot open shared object file: No such file or directory
------
```

I need to report this to https://github.com/rasterio/rasterio-wheels

**Comment by vincentsarago** [comment]
for now I'll stick to ~1.3.9 https://github.com/developmentseed/titiler-md-demo/blob/bde1f21d0dde15b560c3dee635012d1950448796/infrastructure/aws/lambda/lambda.Dockerfile#L19

**Comment by vincentsarago** [comment]
https://github.com/rasterio/rasterio/discussions/3257#discussioncomment-11385860
